### ISSUE TITLE
Event listener for selecting feedback with return key.

### ISSUE THREAD

**Issue by emphaticsunshine** [giangvo/alfred-workflow-nodejs#15]
How do I listen to event when "Feedback A" or "Feedback B" is selected by return key?

**Comment by noise-machines** [comment]
When an item is selected with the return key, the item's `arg` property is passed as the input (also called `query`) to the next node in the workflow. You can't listen for the return key press directly.

The [Alfred docs](https://www.alfredapp.com/help/workflows/inputs/script-filter/json/) have more details.
