### ISSUE TITLE
why examplejs not work

### ISSUE THREAD

**Issue by allentofight** [giangvo/alfred-workflow-nodejs#17]
![8039ac92-b578-46ae-91ed-43143296323f](https://user-images.githubusercontent.com/1235483/33805728-6723d0e4-ddf8-11e7-82d5-5911a2ad924e.png)

as the picture show,after I follow your instruction, when I click "examplejs k", it shows google!what's wrong with it

**Comment by allentofight** [comment]
should change node bash command route

**Comment by giangvo** [comment]
Hi @allentofight, thanks for your feedback. Could u explain it a bit more? Does everything work for you now? Feel free to ping me if u need support :)
