### ISSUE TITLE
I am not understanding the menu API or "feedbacks"

### ISSUE THREAD

**Issue by edasque** [giangvo/alfred-workflow-nodejs#4]
Is there more to feedback that the notification alert?

How can I declare a menu of two options (Say ActionA and ActionB) and handle the event when either is selected?

I am lost between the various properties of each items and what they're for (title,subtitle,arg, hasSubItems, valid, data) unless they're just used for the menu subsystems & feedbacks

Sorry, I am not understanding the documentation. Can you help?

Right now I have this:
```javascript
(function main() {
    actionHandler.onAction("menu", function(query) {
        var Item = AlfredNode.Item;
        // generate feeback A
        var item1 = new Item({
            title: "TV Off",
            subtitle: "Press tab to get menu items",
            arg: "Feedback A",
            hasSubItems: true, // set this to true to tell that this feedback has sub Items
            valid: true,
            data: {
                alias: "X"
            } // we can set data to item to use later to build sub items
        });
        workflow.addItem(item1);

        // generate feeback B
        var item2 = new Item({
            title: "Feedback B",
            subtitle: "Press tab to get menu items",
            arg: "FeedbackB",
            hasSubItems: false, // set this to true to tell that this feedback has sub Items
            valid: true,
            data: {
                alias: "Y"
            } // we can set data to item to use later to build sub items
        });
        workflow.addItem(item2);

        // generate feedbacks
        workflow.feedback();
    });

    actionHandler.onAction("Feedback B", function(query) {
        // your code to handle action 1 here
        workflow.info("Hub IP", "Test");
    });

    AlfredNode.run();
})();
```

**Comment by edasque** [comment]
@giangvo any help?

**Comment by giangvo** [comment]
Hi, sorry for my late response. I was very busy. Now I can help you on this if you still need. Plz comment here.

**Comment by edasque** [comment]
I absolutely still do, thank you

**Comment by giangvo** [comment]
Let me try to explain you a bit about this framework.
- When you open Alfred and type "menu xyz". Code block below will handle it
`actionHandler.onAction("menu", function(query) { ... }`
so you can implement it to return feedback items (e.g Feedback A, FeedbackB,...). The `query` param here is `xyz`, you can use it to filter your feedback items.
- In menu scenario, when you focus on "Feedback A" then press `TAB`. You will see in Alfred:
`menu Feedback A $>` and you can start typing your query. e.g `menu Feedback A $> abc`. Code block below will handle it
`actionHandler.onMenuItemSelected("menuExample", function(query, title, data) {...}`
so here:
query: abc
title: Feedback A
data: previous data that you set to Feedback A (when create it)

Hope it will help. Plz ping me if you have any concerns. 

Regards,
