### ISSUE TITLE
Deeper menus after first onMenuItemSelected

### ISSUE THREAD

**Issue by krokofant** [giangvo/alfred-workflow-nodejs#8]
I have multiple top-level alternatives such as
(Action) Set password + password
(Action) Set user + username
(Action) Get courses
(MenuItemSelected) Get courses + SelectedCourse

Now I would want an additional menu like
(MenuItemSelected) Get courses + SelectedCourse + Register

Is this possible?

**Comment by giangvo** [comment]
Hi, current code does not support. I will think about it and do implementation
